improve the lobby screen
OpenLWR/OpenLWR pull request #8
Opened 2024-04-30 10:46 UTC by kcinnaJlol

see commit messages for more info

2024-05-01 00:00 UTC, watchful5406 requested changes
client should automatically connect to 127.0.0.1:7001 if the ip field is blank (localhost does not accomplish this)

2024-05-01 17:52 UTC, rogerwim requested changes
you should do either localhost:7001 or 127.0.0.1:7001, just localhost or 127.0.0.1 wont work

2024-05-02 23:04 UTC, watchful5406 approved these changes

2024-05-03 01:14 UTC, SakuruWasTaken approved these changes

2024-05-03 01:14 UTC, merged